sudo: required
language: java

services:
  - docker

jdk:
  - oraclejdk8

before_install:
  # Disable services enabled by default
  - sudo service mysql stop
  - sudo /etc/init.d/postgresql stop

  # Run my databases in the background
  - docker-compose -f etc/docker-compose.yml up -d

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check

after_success:
- ./gradlew jacocoReport coveralls

#after_failure:
#- ./gradlew clean check --debug
