sudo: required

language: java

services:
  - docker
  - mysql
  - postgresql

#before_install:
#  - docker-compose -f etc/docker-compose.yml up

jdk:
  - oraclejdk8

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check
