sudo: required
language: java

services:
  - docker

jdk:
  - oraclejdk8

before_install:
  # Disable services enabled by default
  - sudo service mysql stop
  - sudo /etc/init.d/postgresql stop

  # Run my databases in the background
  - docker-compose -f docker/docker-compose-test.yml up -d

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew build testAll codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
